### ISSUE TITLE
swapHeadAndTail

### ISSUE THREAD

**Issue by aorgish** [andreilysiuk/js-assignments#16]
https://github.com/andreilysiuk/js-assignments/blob/b1c02059990babbfa70ad30993c00453d7c50c73/task/04-arrays-tasks.js#L587-L590

Немного прямолинейное решение, с копирование данных туда-сюда.
По сути тут подходит простой `map`, только функцию проекции надо правильно написать. Это непросто, у меня ушел где-то час до более менее лаконичного варианта, так что если не получится - можно оставить как есть.

**Comment by andreilysiuk** [comment]
Средний элемент все портит. Но у меня все равно вышло.
