### ISSUE TITLE
getCommonDirectoryPath

### ISSUE THREAD

**Issue by aorgish** [andreilysiuk/js-assignments#25]
https://github.com/andreilysiuk/js-assignments/blob/b1c02059990babbfa70ad30993c00453d7c50c73/task/06-conditions-n-loops-tasks.js#L436-L445

Этот алгоритм модифицирует входной массив. Плюс я всегда не рекомендую использовать рекурсию, она довольно часто вылетает с ошибкой StackOverflow .

Я бы тут все таки делал двумя вложенными циклами, без всяких модифицикаций исходных данных.

**Comment by andreilysiuk** [comment]
Можно и одним циклом обойтись.
