### ISSUE TITLE
logger

### ISSUE THREAD

**Issue by aorgish** [andreilysiuk/js-assignments#31]
https://github.com/andreilysiuk/js-assignments/blob/b1c02059990babbfa70ad30993c00453d7c50c73/task/09-functions-n-closures-tasks.js#L156-L181

Вместо велосипеда 'getArgsLine' короче 

```
var argsLine = JSON.stringify(Array.from(arguments)).slice(1,-1);
```

**Comment by andreilysiuk** [comment]
Эта задача меня больше всего интересовала. Спасибо за прием.
